spring.application.name=Actlas


spring.datasource.url=jdbc:h2:file:./data/actlas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

imdb.api-base-url=https://api.imdbapi.dev

imdb.jsoup.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
imdb.jsoup.timeout=8000

kinobaza.search-url=https://kinobaza.com.ua/search

actlas.history.max-size=70